name = "Grenades Into Hatches"
author = "Viko"
prefix = "vik_gih"

[files]
exclude = [
	"*.hpp"
]

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[hemtt.release]
sign = true
archive = true
